### ISSUE TITLE
运行出现问题（加密部分）

### ISSUE THREAD

**Issue by Patrick-xiefeng** [SJTUwbl/MaCA#5]
作者你好，我已经成功运行原MaCA代码，但苦于原代码有加密，所以无法完全理解代码含义并进行二次开发（毕设），看到您复现加密代码后想对您表达感激。
但在跑您的程序时遇到如下报错：（按照原MaCA方法做的）
`Traceback (most recent call last):
  File "/home/xie/Desktop/MaCA-master/environment/pytransform.py", line 237, in _load_library
    m = cdll.LoadLibrary(os.path.join(libpath, '_pytransform.so'))
  File "/home/xie/applications/anaconda3/envs/maca/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/xie/applications/anaconda3/envs/maca/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xie/Desktop/MaCA-master/environment/_pytransform.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xie/Desktop/MaCA-master/fight.py", line 17, in <module>
    from interface import Environment
  File "/home/xie/Desktop/MaCA-master/environment/interface.py", line 4, in <module>
    pyarmor_runtime()
  File "/home/xie/Desktop/MaCA-master/environment/pytransform.py", line 274, in pyarmor_runtime
    pyarmor_init(path)
  File "/home/xie/Desktop/MaCA-master/environment/pytransform.py", line 268, in pyarmor_init
    _pytransform = _load_library(path)
  File "/home/xie/Desktop/MaCA-master/environment/pytransform.py", line 248, in _load_library
    raise PytransformError('Could not load _pytransform from "%s"', libpath)
pytransform.PytransformError: ('Could not load _pytransform from "%s"', '/home/xie/Desktop/MaCA-master/environment')

进程已结束，退出代码为 1
`

按照我的理解，应该是加密代码被复现后，后续代码仍想读取加密代码但无法读取的问题。想知道作者是如何解决这个问题的？
感谢。

**Comment by Patrick-xiefeng** [comment]
@SJTUwbl

**Comment by lzh-awesome** [comment]
确实，看了好久才发现代码加密了；train里面的main和train都把render加密了

**Comment by z1z23** [comment]
24年了。我也遇到这个问题了。。。咋解决的？ @Patrick-xiefeng
